services:
    cabot.damaioconfiguration.logo_path_helper:
        class: cabot\damaioconfiguration\helper\logo_path_helper
        arguments:
            - '@path_helper'

    cabot.damaioconfiguration.listener:
        class: cabot\damaioconfiguration\event\listener
        arguments:
        - '@config'
        - '@config_text'
        - '@template'
        - '@cabot.damaioconfiguration.logo_path_helper'
        tags:
            - { name: event.listener }
