services:
    cabot.damaioconfiguration.listener:
        class: cabot\damaioconfiguration\event\listener
        arguments:
        - '@config'
        - '@template'
        tags:
            - { name: event.listener }
